### ISSUE TITLE
Target .net standard 2.0

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [orientechnologies/OrientDB.Net#1]
Since .net standard 2.0 and dotnet core 2.0 have been released, I was wondering if OrientDb.NET could start targeting .net standard 2.0?

**Comment by gar-ema** [comment]
i'm working on this right now

**Comment by mike-echo-oscar-whiskey** [comment]
Do you need help with that?

**Comment by gar-ema** [comment]
closed with merge of PR #2
