### ISSUE TITLE
Communicate what being acquired by CallidusCloud means for the development of this open-source driver

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [orientechnologies/OrientDB.Net#13]
Could you please communicate what being acquired by CallidusCloud means for the future development of this open-source driver?

**Comment by lvca** [comment]
Nothing's changed, OrientDB Community edition will remain Open Source Apache licensed ;-)

**Comment by riker09** [comment]
So the project remains under an open source license, but what about the active development? Last commits where made in september, new tickets are not answered, PRs are not getting merged.
