### ISSUE TITLE
Remove old repositories and migrate issues

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [orientechnologies/OrientDB.Net#8]
The following repositories should be deleted and have their issues migrated to this repository.

https://github.com/orientechnologies/OrientDB.Net.Core
https://github.com/orientechnologies/OrientDB.Net.ConnectionProtocols.Binary
https://github.com/orientechnologies/OrientDB.Net.Serializers.RecordCSVSerializer
https://github.com/orientechnologies/OrientDB.Net.SqlCommandBuilder

**Comment by gar-ema** [comment]
https://github.com/orientechnologies/OrientDB.Net.Core ✔️
https://github.com/orientechnologies/OrientDB.Net.ConnectionProtocols.Binary ✔️
https://github.com/orientechnologies/OrientDB.Net.Serializers.RecordCSVSerializer ✔️
https://github.com/orientechnologies/OrientDB.Net.SqlCommandBuilder ✔️

Issue migrated to this repo. We'll close them shortly

**Comment by riker09** [comment]
The old repositories are still intact. That was kind of confusing when I started working with OrientDB in .NET Core.
